import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Là sao nhỉ",
  description: "Generated by create next app",
  authors: [
    {
      name: "Tên của bạn", // Thay tên tác giả ở đây
      url: "https://www.example.com", // Đường dẫn tới trang cá nhân của tác giả (nếu có)
    },
  ],
  keywords: "từ khóa, liên quan, đến, nội dung", // Thêm từ khóa liên quan
  robots: "index, follow", // Chỉ thị cho robot tìm kiếm
  viewport: "width=device-width, initial-scale=1.0", // Đặt viewport
  openGraph: {
    title: "Là sao nhỉ",
    description: "Generated by create next app",
    url: "https://www.example.com", // Đường dẫn URL của trang
    images: [
      {
        url: "https://www.example.com/image.jpg", // Đường dẫn đến hình ảnh đại diện
        width: 800, // Chiều rộng của hình ảnh
        height: 600, // Chiều cao của hình ảnh
        alt: "Mô tả hình ảnh", // Mô tả hình ảnh
      },
    ],
    type: "website", // Loại trang
  },
  twitter: {
    card: "summary_large_image", // Loại thẻ Twitter
    title: "Là sao nhỉ",
    description: "Generated by create next app",
    images: [
      {
        url: "https://www.example.com/image.jpg", // Đường dẫn đến hình ảnh cho Twitter
        alt: "Mô tả hình ảnh cho Twitter",
      },
    ],
  },
};

export default function TestLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
